server: 
    #服务注册中心端口号
    port: 7001
eureka: 
    instance:
        #服务注册中心实例的主机名
        hostname: eureka7001
    client:
        #是否向服务注册中心注册自己
        register-with-eureka: false
        #是否检索服务
        fetch-registry: false
        service-url: 
            #服务注册中心的配置内容，指定服务注册中心的位置,集群配置暴露另外两个eureka
            defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/